### ISSUE TITLE
Support OAS2 TSV encoding

### ISSUE THREAD

**Issue by chris-miaskowski** [stoplightio/http-spec#10]
Just a quick note:

Our types disallow the use of parameters TSV encoding.

```
	    // case 'tsv':
    //   content.encodings.push({
    //     property: parameter.name,
    //     style: HttpParamStyles.?,
    //     explode: false,
    //   });
    //   break;
```

**User story.**
As a {user_type}, I can do {some_user_action}, so that I can {some_user_value}.

**Is your feature request related to a problem?**

**Describe the solution you'd like**

**Additional context**

**Comment by philsturgeon** [comment]
@chris-miaskowski if this is still relevant could you update it?

**Comment by chohmann** [comment]
I'm going to close this issue since it seems to not be relevant anymore given the lack of info. Feel to re-open and add more context if still relevant.
