### ISSUE TITLE
OAS3 transformation returns parameters which are not included in typings

### ISSUE THREAD

**Issue by mpodlasin** [stoplightio/http-spec#154]
## Describe the bug

There are cases where oas3 transformation includes an `example` parameter on resulting object.

However this property doesn't exist on `IHttpOperation` (and subtypes) at all.

Here is me adding types to an object existing in http-spec test suite (`oas3/__tests__/operation.test.ts` file):

![Screenshot 2021-07-19 at 14 02 18](https://user-images.githubusercontent.com/7916523/126157231-c1e60469-3f8f-4568-8db1-6d3dbcda0160.png)

## Expected behavior

Either:

a) don't include `example` parameter and simply add it to `examples` array
**or**
b) add `example` parameter to `IHttpOperation` typings.

**Bonus points:** properly type all objects tested in test suite, so that this kind of error doesn't happen again.

**Comment by mpodlasin** [comment]
@P0lip @marbemac Can I have your input on that, as you are the top contributors to the library? 🤔

**Comment by P0lip** [comment]
@mpodlasin I'd go for `a)`.  If I am not mistaken I kept `example` for backwards compatibility.

**Comment by marbemac** [comment]
Agree re option `a)` - one of our goals with http-spec is to reduce the million different ways the same thing can be represented in OpenAPI 🤓.
