### ISSUE TITLE
Dependency on lodash.pick Introduces Vulnerabilities

### ISSUE THREAD

**Issue by aikms-maker** [stoplightio/http-spec#263]
Hello,

I'm encountering a security concern in a project that uses the `@stoplight/http-spec` library, specifically relating to its dependency on `lodash.pick`. The concern is about vulnerabilities present in `lodash.pick`.

According to a [comment on the GitHub Lodash repository](https://github.com/lodash/lodash/issues/5808#issuecomment-1909732506), using individual method packages like `lodash.pick` seems not recommended. This is due to the potential lack of frequency in security updates and maintenance compared to the main `lodash` library.

To address this issue, could you consider replacing the usage of `lodash.pick` with the entire `lodash` library, or exploring other alternatives? This could mitigate security risks and enhance the safety of the library.

Thank you for considering this request.

Best regards,

**Comment by lmmcampbell** [comment]
Hi,

We are also encountering this security concern, and would appreciate the replacement of lodash.pick with the entire lodash library. Thanks!

**Comment by daniel-albuschat** [comment]
It is very concerning that fixing this security vulnerability, which is scored as "HIGH" severity, takes over a month, without any response from the maintainers. :-(
