### ISSUE TITLE
Add support for server variables

### ISSUE THREAD

**Issue by lottamus** [stoplightio/http-spec#53]
**User story.**

As an OpenAPI v3 spec, all of my servers and server variables will be included after transforming to an IHttpService.

**Is your feature request related to a problem?**

This feature allows us to display server variables in Docs and replace server variables with their default values in @stoplight/request-maker.

**Describe the solution you'd like**

When [mapping over the http service's servers](https://github.com/stoplightio/http-spec/blob/master/src/oas3/service.ts#L38-L42), we should also include any [server variables](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#server-variable-object) as defined by the [IServer interface](https://github.com/stoplightio/types/blob/master/src/servers.ts#L8)

**Additional context**

- Add a test that ensures we are including all the server variable properties to https://github.com/stoplightio/http-spec/blob/master/src/oas3/__tests__/service.test.ts
- Need by https://github.com/stoplightio/elements/issues/196

**Comment by philsturgeon** [comment]
Make sure we're looking for servers at the global level, and at the Path Item level (i.e servers can sit next to `get`, `post`, etc.) and operation level (servers can sit _inside_ `get`, `post`, etc.)
