### ISSUE TITLE
Postman Collection: inferring schema from XML example

### ISSUE THREAD

**Issue by karol-maciaszek** [stoplightio/http-spec#75]
The transformer should be capable of inferring JSON schema from an XML payload saved in request and/or response of Postman Collection.

This should be similar to how JSON payload treated currently - https://github.com/stoplightio/http-spec/blob/master/src/postman/transformers/params.ts#L67.

**Comment by XVincentX** [comment]
We can definitely try, but that is not going to be that easy. XML had 1232903 ways to be rendered and a copious amount of quirks. We can do a best effort! Let's keep this open, I guess this will be one of the items we could work on when we'll release the Postman Collection beta support in Prism.

**Comment by chohmann** [comment]
@karol-maciaszek @XVincentX is this issue still relevant? Can we close it?

**Comment by XVincentX** [comment]
I do not think this is a priority and likely this feature is not going to be asked by anybody. I'm ok closing it.
